spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
